/**
 * Pure orchestration of system-prompt slimming — no Pi imports, unit-testable.
 *
 * Applies the skill-catalog rewrite (off / compact / hybrid — see skills.ts) to
 * every system text block AND every tool description in an Anthropic-style
 * request body, then optionally slims the `tools` array.
 *
 * The `<available_skills>` catalog can live in the system prompt or inside a
 * tool's description depending on the harness, so both are scanned. Only content
 * is removed/compacted; surviving text is never reordered or rewritten.
 */

import { extractQuery, type SkillMode, type TailStyle, transformSkillsInText } from "./skills.ts";
import { collectUsedToolNames, optimizeTools, type ToolsMode } from "./tools.ts";
import { type SkillOptimizerProfile } from "./profile.ts";

export interface OptimizeConfig {
	/** What to do with the `<available_skills>` catalog: `off` | `compact` | `hybrid`. */
	mode: SkillMode;
	/** hybrid: relevant skills kept at full description + explicit location. */
	topK: number;
	/** hybrid tail style for non-selected skills: `name` or `intent`. */
	tail: TailStyle;
	/** What to do with the `tools` array (off by default — removing a tool has no fallback). */
	toolsMode: ToolsMode;
	/** drop mode: tool name prefixes to remove (e.g. `htb_`, `mcpwn_`). */
	toolsDropPrefixes: readonly string[];
	/** relevance mode: keep this many non-core query-relevant tools. */
	toolsTopK: number;
	/** Extra protected tool names/prefixes. */
	toolsProtect: readonly string[];
	/** User-specific skill retrieval profile generated by `/skill-optimizer init`. */
	profile?: SkillOptimizerProfile;
	/** Usage-derived skills that should stay fully described. */
	pinnedSkills?: readonly string[];
	/** User allowlist: always render these skills full. */
	alwaysFull?: readonly string[];
	/** User denylist: drop these skills from the catalog (exact name or `prefix*`). */
	never?: readonly string[];
}

export interface OptimizeResult {
	next: unknown;
	/** Net characters removed total (skills catalog + tools array). */
	removed: number;
	/** Chars removed by the skills-catalog rewrite (system / systemInstruction / instructions / messages / tool descriptions). */
	removedSkills: number;
	/** Chars removed by slimming the `tools` array. */
	removedTools: number;
	/** Skill names kept at full description on the last system/tool block processed. */
	selected: string[];
	/** Tool names dropped from the `tools` array. */
	droppedTools: string[];
}

interface RequestBody {
	system?: unknown;
	/** Google Gemini system prompt location. */
	systemInstruction?: unknown;
	/** OpenAI Responses system prompt location. */
	instructions?: unknown;
	tools?: unknown;
	messages?: unknown;
	[key: string]: unknown;
}

const SYSTEM_ROLES = new Set(["system", "developer"]);

interface SystemTextBlock {
	type: "text";
	text: string;
	[key: string]: unknown;
}

function isSystemTextBlock(value: unknown): value is SystemTextBlock {
	return (
		!!value &&
		typeof value === "object" &&
		(value as SystemTextBlock).type === "text" &&
		typeof (value as SystemTextBlock).text === "string"
	);
}

type SystemShape = "array" | "block" | "string" | "none";

interface NormalizedSystem {
	shape: SystemShape;
	blocks: unknown[];
}

function normalizeSystem(system: unknown): NormalizedSystem {
	if (Array.isArray(system)) return { shape: "array", blocks: system };
	if (isSystemTextBlock(system)) return { shape: "block", blocks: [system] };
	if (typeof system === "string" && system.length > 0) {
		return { shape: "string", blocks: [{ type: "text", text: system } satisfies SystemTextBlock] };
	}
	return { shape: "none", blocks: [] };
}

function restoreSystem(system: unknown, normalized: NormalizedSystem, blocks: unknown[]): unknown {
	if (normalized.shape === "array") return blocks;
	if (normalized.shape === "block") return blocks[0] ?? system;
	if (normalized.shape === "string") {
		const block = blocks[0];
		return isSystemTextBlock(block) ? block.text : system;
	}
	return system;
}

/** Apply the skill-catalog rewrite to one text string. Returns the new text and the names kept full (hybrid). */
function transformText(text: string, query: string, config: OptimizeConfig): { text: string; selected: string[] } {
	if (config.mode === "off") return { text, selected: [] };
	const r = transformSkillsInText(text, {
		mode: config.mode,
		topK: config.topK,
		tail: config.tail,
		query,
		profile: config.profile,
		pinnedSkills: config.pinnedSkills,
		alwaysFull: config.alwaysFull,
		never: config.never,
	});
	return { text: r.text, selected: r.selected };
}

function hasWork(config: OptimizeConfig): boolean {
	return config.mode !== "off" || config.toolsMode !== "off";
}

/**
 * Slim the skills catalog + tool descriptions + `tools` array of a request body.
 * Provider-agnostic: scans the Anthropic `system`, the Gemini `systemInstruction`,
 * the OpenAI Responses `instructions`, and any `messages` entry with a system or
 * developer role, plus tool descriptions. Returns the original reference (and
 * `removed: 0`) when nothing changed. Pure and idempotent.
 */
export function optimize(payload: unknown, config: OptimizeConfig): OptimizeResult {
	if (!payload || typeof payload !== "object" || !hasWork(config)) {
		return { next: payload, removed: 0, removedSkills: 0, removedTools: 0, selected: [], droppedTools: [] };
	}
	const typed = payload as RequestBody;
	const query = config.mode === "hybrid" || config.toolsMode === "relevance" ? extractQuery(typed.messages) : "";

	let removedSkills = 0;
	let removedTools = 0;
	let changed = false;
	let droppedTools: string[] = [];
	const selected: string[] = [];
	const addSelected = (names: readonly string[]): void => {
		for (const name of names) {
			if (!selected.includes(name)) selected.push(name);
		}
	};
	/** Rewrite a plain string field; returns the new string (or the same when unchanged). */
	const rewriteString = (value: string): string => {
		const r = transformText(value, query, config);
		if (r.text === value) return value;
		removedSkills += value.length - r.text.length;
		addSelected(r.selected);
		changed = true;
		return r.text;
	};

	const next: RequestBody = { ...typed };

	// Anthropic `system` (string | text block | array of text blocks)
	const normalizedSystem = normalizeSystem(typed.system);
	if (normalizedSystem.shape !== "none") {
		let systemChanged = false;
		const blocks = normalizedSystem.blocks.map((block) => {
			if (!isSystemTextBlock(block)) return block;
			const text = rewriteString(block.text);
			if (text === block.text) return block;
			systemChanged = true;
			return { ...block, text };
		});
		if (systemChanged) next.system = restoreSystem(typed.system, normalizedSystem, blocks);
	}

	// Gemini `systemInstruction` (string | { parts: [{ text }] })
	if (typeof typed.systemInstruction === "string") {
		next.systemInstruction = rewriteString(typed.systemInstruction);
	} else if (typed.systemInstruction && typeof typed.systemInstruction === "object") {
		const si = typed.systemInstruction as { parts?: unknown };
		if (Array.isArray(si.parts)) {
			let partsChanged = false;
			const parts = si.parts.map((p) => {
				if (!p || typeof p !== "object" || typeof (p as { text?: unknown }).text !== "string") return p;
				const pt = p as { text: string };
				const text = rewriteString(pt.text);
				if (text === pt.text) return p;
				partsChanged = true;
				return { ...pt, text };
			});
			if (partsChanged) next.systemInstruction = { ...si, parts };
		}
	}

	// OpenAI Responses `instructions` (string)
	if (typeof typed.instructions === "string") {
		next.instructions = rewriteString(typed.instructions);
	}

	// OpenAI / Mistral system|developer messages
	if (Array.isArray(typed.messages)) {
		let messagesChanged = false;
		const messages = typed.messages.map((m) => {
			if (!m || typeof m !== "object") return m;
			const msg = m as { role?: unknown; content?: unknown };
			if (typeof msg.role !== "string" || !SYSTEM_ROLES.has(msg.role)) return m;
			if (typeof msg.content === "string") {
				const content = rewriteString(msg.content);
				if (content === msg.content) return m;
				messagesChanged = true;
				return { ...msg, content };
			}
			if (Array.isArray(msg.content)) {
				let blockChanged = false;
				const content = msg.content.map((b) => {
					if (!b || typeof b !== "object" || typeof (b as { text?: unknown }).text !== "string") return b;
					const bt = b as { text: string };
					const text = rewriteString(bt.text);
					if (text === bt.text) return b;
					blockChanged = true;
					return { ...bt, text };
				});
				if (!blockChanged) return m;
				messagesChanged = true;
				return { ...msg, content };
			}
			return m;
		});
		if (messagesChanged) next.messages = messages;
	}

	// Skills catalog inside a tool description, then slim the tools array itself
	let newTools: unknown = typed.tools;
	if (Array.isArray(typed.tools)) {
		newTools = typed.tools.map((tool) => {
			if (!tool || typeof tool !== "object" || typeof (tool as { description?: unknown }).description !== "string") return tool;
			const t = tool as { description: string };
			const description = rewriteString(t.description);
			if (description === t.description) return tool;
			return { ...t, description };
		});
	}
	if (config.toolsMode !== "off" && Array.isArray(newTools)) {
		const result = optimizeTools(newTools, {
			mode: config.toolsMode,
			dropPrefixes: config.toolsDropPrefixes,
			topK: config.toolsTopK,
			protect: config.toolsProtect,
			keepNames: collectUsedToolNames(typed.messages),
			query,
		});
		if (result.dropped.length > 0) {
			newTools = result.tools;
			removedTools += result.removed;
			droppedTools = result.dropped;
			changed = true;
		}
	}
	if (newTools !== typed.tools) next.tools = newTools;

	if (!changed) return { next: payload, removed: 0, removedSkills: 0, removedTools: 0, selected: [], droppedTools: [] };
	return { next, removed: removedSkills + removedTools, removedSkills, removedTools, selected, droppedTools };
}
