/**
 * Pure orchestration of system-prompt slimming — no Pi imports, unit-testable.
 *
 * Applies the skill-catalog rewrite (off / compact / hybrid — see skills.ts) to
 * every system text block AND every tool description in an Anthropic-style
 * request body, then optionally slims the `tools` array.
 *
 * The `<available_skills>` catalog can live in the system prompt or inside a
 * tool's description depending on the harness, so both are scanned. Only content
 * is removed/compacted; surviving text is never reordered or rewritten.
 */

import { extractQuery, type SkillMode, type TailStyle, transformSkillsInText } from "./skills.ts";
import { collectUsedToolNames, optimizeTools, type ToolsMode } from "./tools.ts";
import { type SkillOptimizerProfile } from "./profile.ts";

export interface OptimizeConfig {
	/** What to do with the `<available_skills>` catalog: `off` | `compact` | `hybrid`. */
	mode: SkillMode;
	/** hybrid: relevant skills kept at full description + explicit location. */
	topK: number;
	/** hybrid tail style for non-selected skills: `name` or `intent`. */
	tail: TailStyle;
	/** What to do with the `tools` array (off by default — removing a tool has no fallback). */
	toolsMode: ToolsMode;
	/** drop mode: tool name prefixes to remove (e.g. `htb_`, `mcpwn_`). */
	toolsDropPrefixes: readonly string[];
	/** relevance mode: keep this many non-core query-relevant tools. */
	toolsTopK: number;
	/** Extra protected tool names/prefixes. */
	toolsProtect: readonly string[];
	/** User-specific skill retrieval profile generated by `/skill-optimizer init`. */
	profile?: SkillOptimizerProfile;
	/** Usage-derived skills that should stay fully described. */
	pinnedSkills?: readonly string[];
	/** User allowlist: always render these skills full. */
	alwaysFull?: readonly string[];
	/** User denylist: drop these skills from the catalog (exact name or `prefix*`). */
	never?: readonly string[];
}

export interface OptimizeResult {
	next: unknown;
	/** Net characters removed across system + tools. */
	removed: number;
	/** Skill names kept at full description on the last system/tool block processed. */
	selected: string[];
	/** Tool names dropped from the `tools` array. */
	droppedTools: string[];
}

interface RequestBody {
	system?: unknown;
	tools?: unknown;
	messages?: unknown;
	[key: string]: unknown;
}

interface SystemTextBlock {
	type: "text";
	text: string;
	[key: string]: unknown;
}

function isSystemTextBlock(value: unknown): value is SystemTextBlock {
	return (
		!!value &&
		typeof value === "object" &&
		(value as SystemTextBlock).type === "text" &&
		typeof (value as SystemTextBlock).text === "string"
	);
}

type SystemShape = "array" | "block" | "string" | "none";

interface NormalizedSystem {
	shape: SystemShape;
	blocks: unknown[];
}

function normalizeSystem(system: unknown): NormalizedSystem {
	if (Array.isArray(system)) return { shape: "array", blocks: system };
	if (isSystemTextBlock(system)) return { shape: "block", blocks: [system] };
	if (typeof system === "string" && system.length > 0) {
		return { shape: "string", blocks: [{ type: "text", text: system } satisfies SystemTextBlock] };
	}
	return { shape: "none", blocks: [] };
}

function restoreSystem(system: unknown, normalized: NormalizedSystem, blocks: unknown[]): unknown {
	if (normalized.shape === "array") return blocks;
	if (normalized.shape === "block") return blocks[0] ?? system;
	if (normalized.shape === "string") {
		const block = blocks[0];
		return isSystemTextBlock(block) ? block.text : system;
	}
	return system;
}

/** Apply the skill-catalog rewrite to one text string. Returns the new text and the names kept full (hybrid). */
function transformText(text: string, query: string, config: OptimizeConfig): { text: string; selected: string[] } {
	if (config.mode === "off") return { text, selected: [] };
	const r = transformSkillsInText(text, {
		mode: config.mode,
		topK: config.topK,
		tail: config.tail,
		query,
		profile: config.profile,
		pinnedSkills: config.pinnedSkills,
		alwaysFull: config.alwaysFull,
		never: config.never,
	});
	return { text: r.text, selected: r.selected };
}

function hasWork(config: OptimizeConfig): boolean {
	return config.mode !== "off" || config.toolsMode !== "off";
}

/**
 * Slim the system prompt + tool descriptions of an Anthropic-style request body.
 * Returns the original reference (and `removed: 0`) when nothing changed.
 * Pure and idempotent.
 */
export function optimize(payload: unknown, config: OptimizeConfig): OptimizeResult {
	if (!payload || typeof payload !== "object" || !hasWork(config)) {
		return { next: payload, removed: 0, selected: [], droppedTools: [] };
	}
	const typed = payload as RequestBody;
	const query = config.mode === "hybrid" || config.toolsMode === "relevance" ? extractQuery(typed.messages) : "";

	let removed = 0;
	let changed = false;
	let selected: string[] = [];
	let droppedTools: string[] = [];
	const addSelected = (names: readonly string[]): void => {
		for (const name of names) {
			if (!selected.includes(name)) selected.push(name);
		}
	};

	const normalizedSystem = normalizeSystem(typed.system);
	let systemChanged = false;
	const newSystemBlocks = normalizedSystem.blocks.map((block) => {
		if (!isSystemTextBlock(block)) return block;
		const r = transformText(block.text, query, config);
		if (r.text === block.text) return block;
		removed += block.text.length - r.text.length;
		addSelected(r.selected);
		changed = true;
		systemChanged = true;
		return { ...block, text: r.text };
	});

	// 1) rewrite the skills catalog where it lives in a tool description
	let newTools: unknown = typed.tools;
	if (Array.isArray(typed.tools)) {
		newTools = typed.tools.map((tool) => {
			if (!tool || typeof tool !== "object" || typeof (tool as { description?: unknown }).description !== "string") {
				return tool;
			}
			const t = tool as { description: string };
			const r = transformText(t.description, query, config);
			if (r.text === t.description) return tool;
			removed += t.description.length - r.text.length;
			addSelected(r.selected);
			changed = true;
			return { ...t, description: r.text };
		});
	}

	// 2) slim the tools array itself (drop / relevance), guarded by core + used
	if (config.toolsMode !== "off" && Array.isArray(newTools)) {
		const result = optimizeTools(newTools, {
			mode: config.toolsMode,
			dropPrefixes: config.toolsDropPrefixes,
			topK: config.toolsTopK,
			protect: config.toolsProtect,
			keepNames: collectUsedToolNames(typed.messages),
			query,
		});
		if (result.dropped.length > 0) {
			newTools = result.tools;
			removed += result.removed;
			droppedTools = result.dropped;
			changed = true;
		}
	}

	if (!changed) return { next: payload, removed: 0, selected: [], droppedTools: [] };
	const next = { ...typed, tools: newTools };
	if (systemChanged) next.system = restoreSystem(typed.system, normalizedSystem, newSystemBlocks);
	return { next, removed, selected, droppedTools };
}
