/**
 * Pure orchestration of system-prompt slimming — no Pi imports, unit-testable.
 *
 * Applies, to every system text block AND every tool description in an
 * Anthropic-style request body:
 *   1. the skill-catalog rewrite (off / strip / compact / hybrid — see skills.ts);
 *   2. removal of any extra configured `<tag>…</tag>` blocks; and
 *   3. removal of blank-line-separated paragraphs containing a configured anchor.
 *
 * The `<available_skills>` catalog can live in the system prompt or inside a
 * tool's description depending on the harness, so both are scanned. Only content
 * is removed/compacted; surviving text is never reordered or rewritten.
 */

import { extractQuery, type SkillMode, transformSkillsInText } from "./skills.ts";
import { collectUsedToolNames, optimizeTools, type ToolsMode } from "./tools.ts";
import { type SkillOptimizerProfile } from "./profile.ts";

export interface OptimizeConfig {
	/** What to do with the `<available_skills>` catalog. */
	mode: SkillMode;
	/** hybrid: relevant skills kept at full description. */
	topK: number;
	/** Max chars for compacted descriptions. */
	tailChars: number;
	/** Keep `<location>` on compacted entries too. */
	keepLocations: boolean;
	/** Extra XML tag names whose whole block is removed (besides skills). */
	extraStripTags: readonly string[];
	/** Substrings; drop whole paragraphs containing one. */
	dropAnchors: readonly string[];
	/** What to do with the `tools` array (off by default — removing a tool has no fallback). */
	toolsMode: ToolsMode;
	/** drop mode: tool name prefixes to remove (e.g. `htb_`, `mcpwn_`). */
	toolsDropPrefixes: readonly string[];
	/** relevance mode: keep this many non-core query-relevant tools. */
	toolsTopK: number;
	/** Extra protected tool names/prefixes. */
	toolsProtect: readonly string[];
	/** User-specific skill retrieval profile generated by `/skill-optimizer init`. */
	profile?: SkillOptimizerProfile;
	/** Usage-derived skills that should stay fully described. */
	pinnedSkills?: readonly string[];
	/** Adaptive top-K guardrails. */
	adaptiveTopK?: boolean;
	minTopK?: number;
	maxTopK?: number;
	/** Weak-query fallback: keep short tail descriptions instead of name-only. */
	safeFallbackTailChars?: number;
}

export interface OptimizeResult {
	next: unknown;
	/** Net characters removed across system + tools. */
	removed: number;
	/** Skill names kept at full description on the last system/tool block processed. */
	selected: string[];
	/** Tool names dropped from the `tools` array. */
	droppedTools: string[];
}

interface RequestBody {
	system?: unknown;
	tools?: unknown;
	messages?: unknown;
	[key: string]: unknown;
}

interface SystemTextBlock {
	type: "text";
	text: string;
	[key: string]: unknown;
}

function isSystemTextBlock(value: unknown): value is SystemTextBlock {
	return (
		!!value &&
		typeof value === "object" &&
		(value as SystemTextBlock).type === "text" &&
		typeof (value as SystemTextBlock).text === "string"
	);
}

type SystemShape = "array" | "block" | "string" | "none";

interface NormalizedSystem {
	shape: SystemShape;
	blocks: unknown[];
}

function normalizeSystem(system: unknown): NormalizedSystem {
	if (Array.isArray(system)) return { shape: "array", blocks: system };
	if (isSystemTextBlock(system)) return { shape: "block", blocks: [system] };
	if (typeof system === "string" && system.length > 0) {
		return { shape: "string", blocks: [{ type: "text", text: system } satisfies SystemTextBlock] };
	}
	return { shape: "none", blocks: [] };
}

function restoreSystem(system: unknown, normalized: NormalizedSystem, blocks: unknown[]): unknown {
	if (normalized.shape === "array") return blocks;
	if (normalized.shape === "block") return blocks[0] ?? system;
	if (normalized.shape === "string") {
		const block = blocks[0];
		return isSystemTextBlock(block) ? block.text : system;
	}
	return system;
}

function escapeRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function stripTagBlock(text: string, tag: string): string {
	if (!tag || !text.includes(`<${tag}`)) return text;
	const block = new RegExp(`<${escapeRegExp(tag)}\\b[\\s\\S]*?</${escapeRegExp(tag)}>\\s*`, "g");
	return text.replace(block, "");
}

function dropParagraphs(text: string, anchors: readonly string[]): string {
	if (anchors.length === 0 || !anchors.some((a) => text.includes(a))) return text;
	return text
		.split(/\n\n+/)
		.filter((paragraph) => !anchors.some((a) => paragraph.includes(a)))
		.join("\n\n");
}

/** Apply all rules to one text string. Returns the new text and the names selected (hybrid). */
function transformText(text: string, query: string, config: OptimizeConfig): { text: string; selected: string[] } {
	let result = text;
	let selected: string[] = [];
	if (config.mode === "strip") {
		result = stripTagBlock(result, "available_skills");
	} else if (config.mode === "compact" || config.mode === "hybrid") {
		const r = transformSkillsInText(result, {
			mode: config.mode,
			topK: config.topK,
			tailChars: config.tailChars,
			keepLocations: config.keepLocations,
			query,
			profile: config.profile,
			pinnedSkills: config.pinnedSkills,
			adaptiveTopK: config.adaptiveTopK,
			minTopK: config.minTopK,
			maxTopK: config.maxTopK,
			safeFallbackTailChars: config.safeFallbackTailChars,
		});
		result = r.text;
		if (r.selected.length > 0) selected = r.selected;
	}
	for (const tag of config.extraStripTags) result = stripTagBlock(result, tag);
	result = dropParagraphs(result, config.dropAnchors);
	return { text: result, selected };
}

function hasWork(config: OptimizeConfig): boolean {
	return (
		config.mode !== "off" ||
		config.toolsMode !== "off" ||
		config.extraStripTags.length > 0 ||
		config.dropAnchors.length > 0
	);
}

/**
 * Slim the system prompt + tool descriptions of an Anthropic-style request body.
 * Returns the original reference (and `removed: 0`) when nothing changed.
 * Pure and idempotent.
 */
export function optimize(payload: unknown, config: OptimizeConfig): OptimizeResult {
	if (!payload || typeof payload !== "object" || !hasWork(config)) {
		return { next: payload, removed: 0, selected: [], droppedTools: [] };
	}
	const typed = payload as RequestBody;
	const query = config.mode === "hybrid" || config.toolsMode === "relevance" ? extractQuery(typed.messages) : "";

	let removed = 0;
	let changed = false;
	let selected: string[] = [];
	let droppedTools: string[] = [];
	const addSelected = (names: readonly string[]): void => {
		for (const name of names) {
			if (!selected.includes(name)) selected.push(name);
		}
	};

	const normalizedSystem = normalizeSystem(typed.system);
	let systemChanged = false;
	const newSystemBlocks = normalizedSystem.blocks.map((block) => {
		if (!isSystemTextBlock(block)) return block;
		const r = transformText(block.text, query, config);
		if (r.text === block.text) return block;
		removed += block.text.length - r.text.length;
		addSelected(r.selected);
		changed = true;
		systemChanged = true;
		return { ...block, text: r.text };
	});

	// 1) rewrite the skills catalog where it lives in a tool description
	let newTools: unknown = typed.tools;
	if (Array.isArray(typed.tools)) {
		newTools = typed.tools.map((tool) => {
			if (!tool || typeof tool !== "object" || typeof (tool as { description?: unknown }).description !== "string") {
				return tool;
			}
			const t = tool as { description: string };
			const r = transformText(t.description, query, config);
			if (r.text === t.description) return tool;
			removed += t.description.length - r.text.length;
			addSelected(r.selected);
			changed = true;
			return { ...t, description: r.text };
		});
	}

	// 2) slim the tools array itself (drop / relevance), guarded by core + used
	if (config.toolsMode !== "off" && Array.isArray(newTools)) {
		const result = optimizeTools(newTools, {
			mode: config.toolsMode,
			dropPrefixes: config.toolsDropPrefixes,
			topK: config.toolsTopK,
			protect: config.toolsProtect,
			keepNames: collectUsedToolNames(typed.messages),
			query,
		});
		if (result.dropped.length > 0) {
			newTools = result.tools;
			removed += result.removed;
			droppedTools = result.dropped;
			changed = true;
		}
	}

	if (!changed) return { next: payload, removed: 0, selected: [], droppedTools: [] };
	const next = { ...typed, tools: newTools };
	if (systemChanged) next.system = restoreSystem(typed.system, normalizedSystem, newSystemBlocks);
	return { next, removed, selected, droppedTools };
}
